title:  Lili-Huang
author:  lilillhuang
email:  lilillhuang@tencent.com
description:  I am a Data Mining Engineer at Tencent, focusing on relevance search and commercial content understanding. Before that, I was a Machine Learning Engineer of advertisement marketing at Vivo. I received my B.S. degree from South China Normal University.
